<html>
  <head>
    <link href="css/styles.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Sriracha&display=swap" rel="stylesheet">
    <title>Lab 6: File Upload</title>
  </head>
  <body>
    <header>
    <img class="image" src="images/cheers-logo.png" alt="Cheers Logo">
    <nav>
      <div class="nav">
        <a href="home.html">Home</a>
        <a href="list_employees.php">Employees</a>
        <a href="list_departments.php">Departments</a>
        </div>
        </nav>
    </header>

    <main>
    <?php

require('connection.php');

echo "<h1>Register New Employee Form</h1>";

echo "<form action='process_employee_registration.php' method='POST'>
      <p class='required'>Employee ID will be auto-generated by the system.</p>
      <section>
      <input type='text' placeholder='First Name' id='first_name' name='first_name' required><span class='required'>required</span>
      </section>
      <section>
      <input type='text' placeholder='Last Name' id='last_name' name='last_name' required><span class='required'>required</span>
      </section>
      <section>
      <input type='text' placeholder='Email' id='email_address' name='email_address' required><span class='required'>required</span>
      </section>
      <section>
      <input type='text' placeholder='Password' id='password' name='password' required><span class='required'>required</span>
      </section>
      <input type='submit'>
      </form>";

?>
<img class="img1" src="images/cheers.jpg">
    </main>
    <footer class="footer">
      <p>&copy Megan Louise Downey - 2023</p>
    </footer>
    </body>
    </html>